PackageIdentifier: shanselman.toasty
PackageVersion: 0.6
ManifestType: installer
ManifestVersion: 1.9.0
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Commands:
  - toasty
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/shanselman/toasty/releases/download/v0.6/toasty-x64.exe
    InstallerSha256: d00283505979931405a422d75b0d13b82223d876a0c7cf17b5b03fc5e50e3b1e
  - Architecture: arm64
    InstallerUrl: https://github.com/shanselman/toasty/releases/download/v0.6/toasty-arm64.exe
    InstallerSha256: fd86f35ed0c37541bfe42a7ba56ff73bc0d3700347b88061a0865e92f9f4f410
